//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCategory
    {
        public string AccountCategoryID { get; set; }
        public string AccountCategoryName { get; set; }
        public int AccountCategoryKind { get; set; }
        public bool DetailByAccountingObject { get; set; }
        public bool DetailByInventoryItem { get; set; }
        public bool DetailByJob { get; set; }
        public bool DetailByContract { get; set; }
        public Nullable<int> AccountingObjectType { get; set; }
        public bool DetailByBankAccount { get; set; }
    }
}
