//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomerPeriod
    {
        public string CompanyCode { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public string AccountNumber { get; set; }
        public string AccountingObjectCode { get; set; }
        public string AccountingObjectName { get; set; }
        public decimal NoDK { get; set; }
        public decimal CoDK { get; set; }
        public decimal PSNo { get; set; }
        public decimal PSCo { get; set; }
        public decimal LKNo { get; set; }
        public decimal LKCo { get; set; }
        public decimal NoCK { get; set; }
        public decimal CoCK { get; set; }
    }
}
