//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoBangCanDoiTaiKhoan
    {
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> NoDK { get; set; }
        public Nullable<decimal> CoDK { get; set; }
        public Nullable<decimal> PSNo { get; set; }
        public Nullable<decimal> PSCo { get; set; }
        public Nullable<decimal> LKNo { get; set; }
        public Nullable<decimal> LKCo { get; set; }
        public Nullable<decimal> NoCK { get; set; }
        public Nullable<decimal> CoCK { get; set; }
    }
}
