//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTonKho
    {
        public string CompanyCode { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public string InventoryItemCode { get; set; }
        public string InventoryItemName { get; set; }
        public string Unit { get; set; }
        public decimal UnitPrice { get; set; }
        public string StockCode { get; set; }
        public Nullable<decimal> QuantityDK { get; set; }
        public Nullable<decimal> AmountDK { get; set; }
        public Nullable<decimal> QuantityNTK { get; set; }
        public Nullable<decimal> AmountNTK { get; set; }
        public Nullable<decimal> QuantityXTK { get; set; }
        public Nullable<decimal> AmountXTK { get; set; }
        public Nullable<decimal> QuantityCK { get; set; }
        public Nullable<decimal> AmountCK { get; set; }
        public Nullable<decimal> QuantityNTK2 { get; set; }
        public Nullable<decimal> AmountNTK2 { get; set; }
        public Nullable<decimal> QuantityXTK2 { get; set; }
        public Nullable<decimal> AmountXTK2 { get; set; }
        public Nullable<decimal> QuantityCK2 { get; set; }
        public Nullable<decimal> AmountCK2 { get; set; }
    }
}
