//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoCongNoQuaHan
    {
        public string CompanyCode { get; set; }
        public System.DateTime ngaychungtu { get; set; }
        public System.Guid StockID { get; set; }
        public System.Guid AccountingObjectID { get; set; }
        public string Branch { get; set; }
        public string AccountingObjectCode { get; set; }
        public string AccountingObjectName { get; set; }
        public Nullable<decimal> HanMuc { get; set; }
        public Nullable<decimal> ToiDa { get; set; }
        public Nullable<decimal> No { get; set; }
        public Nullable<decimal> QuaHan { get; set; }
        public Nullable<decimal> Tren30Ngay { get; set; }
        public Nullable<decimal> Tren60Ngay { get; set; }
        public Nullable<decimal> Tren90Ngay { get; set; }
        public Nullable<decimal> Tren6Thang { get; set; }
        public Nullable<decimal> VuotHanMuc { get; set; }
        public string HopDong { get; set; }
    }
}
