//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTinhHinhThucHienNghiaVuNN
    {
        public int STT { get; set; }
        public int OrderID { get; set; }
        public string ChiTieu { get; set; }
        public string MaSo { get; set; }
        public Nullable<decimal> NoDK { get; set; }
        public Nullable<decimal> NoPS { get; set; }
        public Nullable<decimal> CoPS { get; set; }
        public Nullable<decimal> NoLK { get; set; }
        public Nullable<decimal> CoLK { get; set; }
        public Nullable<decimal> NoCK { get; set; }
    }
}
