//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Job { get; set; }
        public string Phone { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CEO { get; set; }
        public string DGM { get; set; }
        public string ChiefAccountant { get; set; }
        public string Cashier { get; set; }
        public string Version { get; set; }
        public string Title { get; set; }
        public string Province { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> Dongia { get; set; }
    }
}
