//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public System.Guid ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string DanhMuc1 { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
        public string Phieu { get; set; }
    }
}
