//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrist
    {
        public System.Guid DistristID { get; set; }
        public string DistristCode { get; set; }
        public string DistristName { get; set; }
        public string Description { get; set; }
        public System.Guid ProvinceID { get; set; }
    }
}
