//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamacoV3Entities : DbContext
    {
        public HamacoV3Entities()
            : base("name=HamacoV3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountCategory> AccountCategories { get; set; }
        public virtual DbSet<AccountingObject> AccountingObjects { get; set; }
        public virtual DbSet<BaoCaoBangCanDoiKeToan> BaoCaoBangCanDoiKeToans { get; set; }
        public virtual DbSet<BaoCaoBangCanDoiKeToan_Period> BaoCaoBangCanDoiKeToan_Period { get; set; }
        public virtual DbSet<BaoCaoBangCanDoiTaiKhoan> BaoCaoBangCanDoiTaiKhoans { get; set; }
        public virtual DbSet<BaoCaoCongNoQuaHan> BaoCaoCongNoQuaHans { get; set; }
        public virtual DbSet<BaoCaoKetQuaHoatDongKinhDoanh> BaoCaoKetQuaHoatDongKinhDoanhs { get; set; }
        public virtual DbSet<BaoCaoLuuChuyenTienTe> BaoCaoLuuChuyenTienTes { get; set; }
        public virtual DbSet<BaoCaoTinhHinhThucHienNghiaVuNN> BaoCaoTinhHinhThucHienNghiaVuNNs { get; set; }
        public virtual DbSet<BaoCaoTonKho> BaoCaoTonKhoes { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
        public virtual DbSet<Distrist> Distrists { get; set; }
        public virtual DbSet<FIDocument> FIDocuments { get; set; }
        public virtual DbSet<FIDocumentDetail> FIDocumentDetails { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<InventoryItemCategory> InventoryItemCategories { get; set; }
        public virtual DbSet<MMDocument> MMDocuments { get; set; }
        public virtual DbSet<MMDocumentDetail> MMDocumentDetails { get; set; }
        public virtual DbSet<MSC_User> MSC_User { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<TransactionFav> TransactionFavs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Transactions_DynamicReport> Transactions_DynamicReport { get; set; }
        public virtual DbSet<UserJoinRole> UserJoinRoles { get; set; }
        public virtual DbSet<UserJoinStock> UserJoinStocks { get; set; }
        public virtual DbSet<UserJoinStock_Approve> UserJoinStock_Approve { get; set; }
        public virtual DbSet<TableImport> TableImports { get; set; }
        public virtual DbSet<AccountPeriod> AccountPeriods { get; set; }
        public virtual DbSet<AccountCustomerPeriod> AccountCustomerPeriods { get; set; }
        public virtual DbSet<AccountCustomerStockPeriod> AccountCustomerStockPeriods { get; set; }
    }
}
