//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public System.Guid InventoryItemID { get; set; }
        public string CompanyCode { get; set; }
        public System.Guid InventoryCategoryID { get; set; }
        public string InventoryItemCode { get; set; }
        public string BarCode { get; set; }
        public string InventoryItemName { get; set; }
        public string GuarantyPeriod { get; set; }
        public string Unit { get; set; }
        public string ConvertUnit { get; set; }
        public Nullable<decimal> ConvertRate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.Guid> DefaultStockID { get; set; }
        public string InventoryAccount { get; set; }
        public string COGSAccount { get; set; }
        public string SaleAccount { get; set; }
        public Nullable<int> CostMethod { get; set; }
        public Nullable<decimal> MinimumStock { get; set; }
        public Nullable<System.Guid> AccountingObjectID { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<bool> IsTool { get; set; }
        public Nullable<int> InventoryItemType { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public bool Inactive { get; set; }
        public Nullable<decimal> SalePrice1 { get; set; }
        public Nullable<decimal> SalePrice2 { get; set; }
        public string SaleDescription { get; set; }
        public string PurchaseDescription { get; set; }
        public string ItemSource { get; set; }
        public Nullable<bool> IsToolAndInventoryItem { get; set; }
        public Nullable<System.Guid> InventoryCategorySpecialTaxID { get; set; }
        public Nullable<bool> PrintMetarial { get; set; }
        public Nullable<System.Guid> Parent { get; set; }
    
        public virtual InventoryItemCategory InventoryItemCategory { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
