//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMDocument
    {
        public System.Guid RefID { get; set; }
        public string MMDoc { get; set; }
        public string CompanyCode { get; set; }
        public string StockCode1 { get; set; }
        public string StockCode2 { get; set; }
        public int RefType { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime RefDate { get; set; }
        public string RefNo { get; set; }
        public string MMHeader { get; set; }
        public string AccountingObjectCode { get; set; }
        public string AccountingObjectName { get; set; }
        public string AccountingObjectAddress { get; set; }
        public string CompanyTaxCode { get; set; }
        public string ContactName { get; set; }
        public int Posted { get; set; }
        public string UserName2 { get; set; }
        public string UserName { get; set; }
        public int INOut { get; set; }
        public Nullable<int> Factory { get; set; }
        public string Taixe { get; set; }
        public string CMND { get; set; }
        public string Dienthoai { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TaxCode { get; set; }
    }
}
