//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMDocumentDetail
    {
        public System.Guid RefDetailID { get; set; }
        public string MMDoc { get; set; }
        public string CompanyCode { get; set; }
        public string InventoryItemCode { get; set; }
        public string InventoryItemName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityConvert { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string StockCode { get; set; }
        public Nullable<decimal> QuantityCK { get; set; }
        public Nullable<decimal> QuantityCK2 { get; set; }
        public Nullable<int> Posted { get; set; }
        public Nullable<int> RefType { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string MMHeader { get; set; }
        public Nullable<int> INOut { get; set; }
    }
}
