//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.InventoryItems = new HashSet<InventoryItem>();
        }
    
        public string CompanyCode { get; set; }
        public System.Guid StockID { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> BranchID { get; set; }
        public string DefaultAccountNumber { get; set; }
        public bool Inactive { get; set; }
        public Nullable<bool> LPG { get; set; }
        public Nullable<System.Guid> Parent { get; set; }
        public string Province { get; set; }
        public string Code { get; set; }
        public string InvName { get; set; }
        public string Note { get; set; }
        public string TDV { get; set; }
        public string TK { get; set; }
        public string LV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
    }
}
