//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionCode { get; set; }
        public string TransactionName { get; set; }
        public string FormName { get; set; }
        public Nullable<int> SortNo { get; set; }
        public Nullable<int> IsParent { get; set; }
        public string ParentFolder { get; set; }
        public string RoleCode { get; set; }
        public Nullable<int> IsDisplay { get; set; }
        public Nullable<int> IsDynamic { get; set; }
        public string ProcedureName { get; set; }
    }
}
