//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMACO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions_DynamicReport
    {
        public string TransactionCode { get; set; }
        public string FieldName { get; set; }
        public string FieldNameVN { get; set; }
        public string TypeName { get; set; }
        public int IsInput { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> IsSum { get; set; }
    }
}
